Repository LBC-LNBio/KVFinder-web-portal, pull requests merged in 2023-03, with the labels that each got.

#25 Dev
  Dockerfile
  kvfinder-web-portal/DESCRIPTION
  kvfinder-web-portal/NAMESPACE
  kvfinder-web-portal/R/app_server.R
  kvfinder-web-portal/R/app_ui.R
  kvfinder-web-portal/R/mod_server_changeCAVcolor.R
  kvfinder-web-portal/R/mod_server_checkResults.R
  kvfinder-web-portal/R/mod_server_createWORKscene.R
  kvfinder-web-portal/R/mod_server_selectCAV.R
Labels: enhancement

#33 Update KVFinder-web UI
  README.md
  kvfinder-web-portal/R/app_ui.R
  kvfinder-web-portal/R/mod_kvAbout.R
  kvfinder-web-portal/R/mod_kvHelp.R
  kvfinder-web-portal/R/mod_kvTutorial.R
  kvfinder-web-portal/R/mod_ui_kvAbout.R
  kvfinder-web-portal/inst/app/www/depth-characterization-scheme.png
  kvfinder-web-portal/inst/app/www/hydropathy-characterization-scheme.png
  kvfinder-web-portal/inst/app/www/kvfinder-web-schema.png
Labels: documentation, enhancement

#34 change ggplot hyd scale to png
  kvfinder-web-portal/R/app_server.R
  kvfinder-web-portal/R/app_ui.R
  kvfinder-web-portal/inst/app/www/hydropathy_scale.png
  kvfinder-web-portal/inst/app/www/hydropathy_scale.svg
Labels: enhancement

#35 Update hydropathy and depth scales
  Dockerfile
  kvfinder-web-portal/DESCRIPTION
  kvfinder-web-portal/R/app_server.R
  kvfinder-web-portal/R/app_ui.R
  kvfinder-web-portal/R/mod_kvHelp.R
  kvfinder-web-portal/R/mod_server_checkResults.R
  kvfinder-web-portal/R/mod_server_submitJob.R
  kvfinder-web-portal/inst/app/www/hydropathy_scale.png
  kvfinder-web-portal/inst/app/www/hydropathy_scale.svg
Labels: bug, documentation, enhancement

#37 task list changes
  kvfinder-web-portal/R/mod_server_colorCAVdepth.R
  kvfinder-web-portal/R/mod_server_colorCAVhyd.R
  kvfinder-web-portal/R/mod_server_createWORKscene.R
  kvfinder-web-portal/R/mod_server_selectCAV.R
  kvfinder-web-portal/R/mod_server_submitJob.R
  kvfinder-web-portal/man/kv_about.Rd
Labels: bug, enhancement

#36 Update website banner
  kvfinder-web-portal/R/mod_server_submitJob.R
  kvfinder-web-portal/inst/app/www/cover.png
Labels: enhancement

#38 Update interface residue visualization
  kvfinder-web-portal/R/mod_server_interfaceRES.R
  kvfinder-web-portal/R/mod_server_selectCAV.R
Labels: bug

#40 Update Tutorial page
  kvfinder-web-portal/R/mod_kvTutorial.R
  kvfinder-web-portal/inst/app/www/tutorial-retrieve-job-results.png
  kvfinder-web-portal/inst/app/www/tutorial-retrieve-job.png
  kvfinder-web-portal/inst/app/www/tutorial-step2-ba-mode4.png
  kvfinder-web-portal/inst/app/www/tutorial-step2-la-mode3.png
  kvfinder-web-portal/inst/app/www/tutorial-step2-wp-mode1-info.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-ba-mode4.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode1-check-results.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode1-pdb.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode1-toml.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode1-view.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode1-view2.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode1-view3.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode2-po8-vc500.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode2-rd12-vc500.png
  kvfinder-web-portal/inst/app/www/tutorial-step3-wp-mode2-vc500.png
Labels: documentation

#41 fix bug when cav_rep_list is NULL
  kvfinder-web-portal/R/app_server.R
Labels: bug
